version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=${API_URL}
      - VITE_CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
    ports:
      - '3001:3001'
    environment:
      - MONGO_URI=${MONGO_URI}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - EXCHANGE_RATE_API_KEY=${EXCHANGE_RATE_API_KEY}
    volumes:
      - ./backend:/app
      - /app/node_modules
